language: objective-c

notifications:
  - email: false

before_install:
  # osx helper utility
  - python --version && pip --version
  - sudo pip install --egg py2app
  - python gradle/osx/utility/setup.py py2app
  - tar cfvz src/main/resources/org/syncany/gui/helper/Syncany.app.tar.gz -C dist/ Syncany.app