language: java

before_install:
  # osx helper utility
  - python -v || sudo apt-get install python
  - sudo pip install py2app
  - python gradle/osx/utility/setup.py py2app
  - tar cfvz src/main/resources/org/syncany/gui/helper/Syncany.app.tar.gz -C dist/ Syncany.app

install:
  - ls -al .
  - find src/main/resources/org/syncany/gui/helper/