language: java

notifications:
  - email: false

before_install:
  - mkdir -p src/main/resources/org/syncany/gui/helper/
  - ls -al .

install:
  - ls -al .
  - find src/main/resources/org/syncany/gui/helper/